name: parse_rest_api
description: A CloudFirestore inspired Wrapper for Parse REST API.
version: 0.0.1
homepage: https://github.com/jannikhst/parse_rest_api

environment:
  sdk: '>=2.8.0 <3.0.0'
  

dependencies:
  http: ^0.12.2

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
